label music:

    init python:
        renpy.music.register_channel("music2", "music", True)
    # define music tracks. God, I hate this.

    define audio.msTania = ("music/justTania.ogg")
    define audio.taniaHappy = ("music/taniaHappy.ogg")
    define audio.sadCass = ("music/sadCass.ogg")
    define audio.robin = ("music/robin.ogg")
    define audio.robinChoir = ("music/robinChoir.ogg")
    define audio.lichelle = ("music/lichelle.ogg")
    define audio.introspection = ("music/introspection.ogg")
    define audio.tension = ("music/tension.ogg")
    define audio.jazzNoodle = ("music/jazzNoodle.ogg")
    define audio.cheerfulGuitar = ("music/cheerfulGuitar.ogg")
    define audio.cassPiano = ("music/cassPiano.ogg")
    define audio.hallwayChats = ("music/hallwayChats.ogg")
    define audio.kylieFightsBack = ("music/kylieFightsBack.ogg")
    define audio.ringRejection = ("music/ringRejection.ogg")
    define audio.onTheNod = ("music/onTheNod.ogg")
    define audio.mortimer = ("music/mortimer.ogg")
    define audio.toughDiscussion = ("music/toughDiscussion.ogg")
    define audio.bedroom = ("music/bedroom.ogg")
    define audio.darkNoodle = ("music/darkNoodle.ogg")
    define audio.competition = ("music/competition.ogg")
    define audio.battle = ("music/battle.ogg")
    define audio.fountainWater = ("music/fountainWater.ogg")
    define audio.ecg = ("music/ecg.ogg")
    define audio.flatline = ("music/fountainWater.ogg")
    define audio.beep = ("music/beep.ogg")
    define audio.robinReverse = ("music/robinReverse.ogg")
    define audio.tensionReverse = ("music/tensionReverse.ogg")
    define audio.fountainWaterReverse = ("music/fountainWaterReverse.ogg")
    define audio.heart = ("music/heartbeat.ogg")
    define audio.doorKnock = ("music/doorKnock.ogg")
    define audio.wreckagenesis = ("music/wreckagenesis.ogg")

